COMPILER = gcc
FLAGS    = -Wall -lGL -lglut -lGLU
OBJDIR   = obj
SRCDIR   = src
GLDIRS=-I/usr/X11/include/ -L/usr/X11/lib/

it: $(OBJDIR)/ptsviewer.o
	$(COMPILER) $(FLAGS) $(GLDIRS) $(OBJDIR)/*.o -o ptsviewer

$(OBJDIR)/ptsviewer.o: $(SRCDIR)/ptsviewer.c $(SRCDIR)/ptsviewer.h
	@mkdir -p $(OBJDIR)
	$(COMPILER) $(GLDIRS) $(FLAGS) -c $(SRCDIR)/ptsviewer.c -o $(OBJDIR)/ptsviewer.o

test: all
	./ptsviewer

clean:
	rm -rf *~ $(OBJDIR) ptsviewer

all: clean it
