.TH PTSVIEVER 1 ptsviewer\-VERSION
.SH NAME
ptsviewer \- simple pointcloud viewer
.SH SYNOPSIS
.B ptsviewer
.RB "ptsfile"
.SH DESCRIPTION
ptsviewer is a simple OpenGL based viewer for pointclouds stored in a pts file.
Both colored and non colored pointclouds are supported.
.SH USAGE
.B Mouse\-Drag left
Rotate pointcloud.
.TP
.B Mouse\-Drag right
Move up/down, left/right.
.TP
.B Scroll\-Up
Move forward (fast).
.TP
.B Scroll\-Down
Move backward (fast).
.TP
.B +
Increase zoom level.
.TP
.B -
Decrease zoom level.
.TP
.B i
Increase size of points.
.TP
.B o
Reset size of points.
.TP
.B p
Decrease size of points.
.TP
.B a
Move left.
.TP
.B d
Move right.
.TP
.B w
Move forward.
.TP
.B s
Move backward.
.TP
.B q
Move up.
.TP
.B e
Move down.
.TP
.B A
Move left (fast).
.TP
.B D
Move right (fast).
.TP
.B W
Move forward (fast).
.TP
.B S
Move backward (fast).
.TP
.B Q
Move up (fast).
.TP
.B E
Move down (fast).
.TP
.B j
Jump to start position.
.TP
.B f
Flip pointcloud.
.TP
.B x
Invert x rotation.
.TP
.B y
Invert y rotation.
.TP
.B Escape
Quit program.
.SH SEE ALSO
http://rab.informatik.uos.de:3000
.SH BUGS
Please report them!
