.TH PTSVIEVER 1 ptsviewer\-VERSION
.SH NAME
ptsviewer \- simple point cloud viewer
.SH SYNOPSIS
.B ptsviewer
.RB "ptsfile1 [ptsfile2 ...]"
.SH DESCRIPTION
ptsviewer is a simple OpenGL based viewer for point clouds stored as pts or ply
file. In Ply files the either the element “vertex” or the element “point” is
loaded as point cloud data. If both elements are present, the “point” element
data is preferred.  Both colored and non colored point clouds are supported.
Multiple clouds can be loaded and pose estimations for matching can be created.
.SH PTS FILE FORMAT
The pts file format is designed to store point clouds in a simple, human
readable way. Each point is stored as a couple of values in one line of the pts
file. One line contains at least three values, representing the x-, y- and
z-position of the point in a three-dimensional cartesian coordinate system. If
one line has six or more values, it is assumed that the last three values
represent color information as 8-bit vales in a rgb color space. Additional
information (like remission values, accuracy, ...) may be stored between these
to sets of values. They are ignored.

Example of a pts file containing values for position, color and accuracy:

...
-101.132004  -16.282200   -1.671650    9672.242188  88  69  60
 -97.345001  -23.159800   -1.601770    9324.614258  88  69  60
 -96.522903    5.354720   -3.460280    9934.269531  86  69  63
 -96.475403    5.382280   -1.612710    9622.832031  86  69  63
 -95.455399    5.657920   -3.712910    9886.268555  86  69  63
...
.SH COORDINATE SYSTEM
The coordinate system is set to the following:
.br
   x    z
.br
   |  /               
.br
   | /                
.br
   +–––––y            
.br
This is not identical to the OpenGL coordinate system! But it is hopefully the
same as all other software developed at the University of Osnabrück.
.SH USAGE
.TP
.B Mouse\-Drag left
Rotate point cloud.
.TP
.B Mouse\-Drag right
Move up/down, left/right.
.TP
.B Scroll\-Up
Move forward
.TP
.B Scroll\-Down
Move backward
.SH NORMAL MODE
This mode is the main mode for viewing point clouds. If you do not intend to
modify any clouds or generate .pose files for them, you should always stay in
this mode. After starting the ptsviewer you are automatically in this mode.
.TP
.B +,-
Increase/Decrease zoom level.
.TP
.B i,p
Increase/Decrease size of points.
.TP
.B o
Reset size of points.
.TP
.B a,d
Move left/right.
.TP
.B w,s
Move forward/backward.
.TP
.B q,e
Move up/down.
.TP
.B A,D
Move left/right (slow).
.TP
.B W,S
Move forward/backward (slow).
.TP
.B Q,E
Move up/down (slow).
.TP
.B j
Jump to start position.
.TP
.B f
Flip point cloud.
.TP
.B x,y
Invert x/y rotation.
.TP
.B 0...9
Toggle visibility of point clouds 0 to 9.
.TP
.B *
 Increase movement speed.
.TP
.B /
 Decrease movement speed.
.TP
.B u
Deselect all clouds.
.TP
.B t
Toggle visibility of all point clouds.
.TP
.B c
Invert background color.
.TP
.B Return
Enter selection mode.
.TP
.B m
Enter move mode.
.TP
.B Escape
Quit program.
.SH SELECTION MODE
This mode is for selecting point clouds. You can enter either the index number
of one point cloud to select or a list of indices separated by comma.
.TP
.B 0...9
Enter cloud number.
.TP
.B ,
Separate two cloud numbers.
.TP
.B Return
Apply selection.
.TP
.B Escape
Cancel selection.
.SH MOVE MODE
This mode is for modifying the pose of point clouds. You can move them around,
rotate them and store/load these pose rearrangements as .pose file for use in
the 3D-Toolkit (6dslam).
.TP
.B a,d
Move left/right.
.TP
.B w,s
Move forward/backward.
.TP
.B q,e
Move up/down.
.TP
.B A,D
Move left/right (slow).
.TP
.B W,S
Move forward/backward (slow).
.TP
.B Q,E
Move up/down (slow).
.TP
.B r,f
Rotate around x-axis.
.TP
.B t,g
Rotate around y-axis.
.TP
.B z,h
Rotate around z-axis.
.TP
.B R,F
Rotate around x-axis (slow).
.TP
.B T,G
Rotate around y-axis (slow).
.TP
.B Z,H
Rotate around z-axis (slow).
.TP
.B p
Print pose.
.TP
.B P
Generate pose files in current directory.
.TP
.B L
Load pose files for selected clouds from current directory.
.TP
.B l
Load pose files for selected clouds from cloud directory.
.TP
.B m,Escape
Return to normal mode.
.SH LICENSE
This project is licensed under the terms of the Simplified BSD License. For
more details have a look at the license file which comes along with this
software or can be found at
https://github.com/lkiesow/ptsviewer/blob/master/license
.SH SEE ALSO
.TP
.B Project page on github.com:
https://github.com/lkiesow/ptsviewer
.TP
.B 3D-Toolkit, including 6dslam for point cloud registration:
http://slam6d.sourceforge.net/
.SH BUGS
Please report them!
